# Generated by Django 5.2.7 on 2025-10-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_date_alter_exam_duration_alter_exam_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='time_taken',
            field=models.IntegerField(),
        ),
    ]
