# Generated by Django 5.2.7 on 2025-10-13 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_exam_date_alter_exam_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='time_taken',
            field=models.IntegerField(help_text='Time taken in minutes'),
        ),
    ]
