# Generated by Django 5.2.7 on 2025-10-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_exam_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='selected_option',
            new_name='Selected_option',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Option a'), ('B', 'Option b'), ('C', 'Option c'), ('D', 'Option d')], default='A', max_length=1),
        ),
    ]
