# Generated by Django 5.2.7 on 2025-10-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_alter_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexam',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='time_taken',
            field=models.IntegerField(),
        ),
    ]
