# Generated by Django 5.2.7 on 2025-10-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_remove_studentexam_submitted_at_alter_exam_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correct_option',
        ),
    ]
