# Generated by Django 5.2.7 on 2025-10-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
    ]
