# Generated by Django 5.2.7 on 2025-10-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_remove_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]

