# Generated by Django 5.2.7 on 2025-10-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_studentexam_accuracy_studentexam_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexam',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='submitted_at',
        ),
    ]
