# Generated by Django 5.2.7 on 2025-10-16 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_remove_studentexam_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
