# Generated by Django 5.2.7 on 2025-10-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_studentexam_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentexam',
            old_name='total_questions',
            new_name='total',
        ),
    ]
